<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="TEST-010" failures="1" tests="10" name="employeeScripts.EmployeeCreatePostScripts" time="166.143" errors="0" timestamp="2023-02-16T17:17:44 IST" skipped="1">
  <testcase classname="employeeScripts.EmployeeCreatePostScripts" name="UploadText" time="12.693"/>
  <system-out/>
  <testcase classname="employeeScripts.EmployeeCreatePostScripts" name="UploadImage" time="14.525"/>
  <system-out/>
  <testcase classname="employeeScripts.EmployeeCreatePostScripts" name="UploadVideo" time="18.727"/>
  <system-out/>
  <testcase classname="employeeScripts.EmployeeCreatePostScripts" name="Upload_youtube_Url" time="14.027"/>
  <system-out/>
  <testcase classname="employeeScripts.EmployeeCreatePostScripts" name="upload_Five_Images" time="20.732"/>
  <system-out/>
  <testcase classname="employeeScripts.EmployeeCreatePostScripts" name="upload_FivePlus_Images" time="18.561">
    <skipped/>
  </testcase> <!-- upload_FivePlus_Images -->
  <system-out/>
  <testcase classname="employeeScripts.EmployeeCreatePostScripts" name="upload_FivePlus_Images" time="21.124"/>
  <system-out/>
  <testcase classname="employeeScripts.EmployeeCreatePostScripts" name="UploadVideo_Multiple" time="16.183">
    <failure message="expected [Upload Count : 2] but found [Upload Count : 1]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Upload Count : 2] but found [Upload Count : 1]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at employeeScripts.EmployeeCreatePostScripts.UploadVideo_Multiple(EmployeeCreatePostScripts.java:219)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
    </failure>
  </testcase> <!-- UploadVideo_Multiple -->
  <system-out/>
  <testcase classname="employeeScripts.EmployeeCreatePostScripts" name="Status_archieve" time="14.469"/>
  <system-out/>
  <testcase classname="employeeScripts.EmployeeCreatePostScripts" name="UploadImageAndCancel" time="15.102"/>
  <system-out/>
</testsuite> <!-- employeeScripts.EmployeeCreatePostScripts -->
